name: pypsa-eur
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - pip

  - pypsa>=0.14

  # Dependencies of the workflow itself
  - xlrd
  - scikit-learn
  - pycountry
  - seaborn
  - snakemake-minimal
  - memory_profiler

  # Second order dependencies which should really be deps of atlite
  - xarray
  - bottleneck
  - toolz
  - dask
  - progressbar2

  # Include ipython so that one does not inadvertently drop out of the conda
  # environment by calling ipython
  - ipython

  # GIS dependencies have to come all from conda-forge
  - conda-forge::cartopy
  - conda-forge::fiona
  - conda-forge::pyproj
  - conda-forge::pyshp
  - conda-forge::geopandas
  - conda-forge::rasterio
  - conda-forge::shapely
  - conda-forge::libgdal

  # The FRESNA/KIT stuff is not packaged for conda yet
  - pip:
    - vresutils>=0.2.5
    - git+https://github.com/FRESNA/atlite.git#egg=atlite
    - git+https://github.com/PyPSA/glaes.git#egg=glaes
    - git+https://github.com/PyPSA/geokit.git#egg=geokit
    #- git+https://github.com/FRESNA/powerplantmatching.git#egg=powerplantmatching
